### ISSUE TITLE
unknown error on server restart

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/SlimyRepair#1]
## Description (Required)

No idea. Just caught it in the console upon restart.

## Steps to reproduce the Issue (Required)

no clue

## Server Log / Error Report

https://pastebin.com/UZ4f3qw1

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: removed
 - Slimefun Version: 803
 - Plugin Version: dev 2

**Comment by NCBPFluffyBear** [comment]
Fixed in latest, thank you.
