### ISSUE TITLE
error repairing slimfun items

### ISSUE THREAD

**Issue by goldenpunch101** [NCBPFluffyBear/SlimyRepair#2]
## Description (Required)

Im geting an error trying to repair items for slimfun, i try 40 to 100 always getting the same error in console.

This is the code for the repair items

GILDED_IRON_HELMET:
  material: GILDED_IRON
  material-type: SLIMEFUN
  repair-amount: 50

GILDED_IRON_CHESTPLATE:
  material: GILDED_IRON
  material-type: SLIMEFUN
  repair-amount: 35

GILDED_IRON_LEGGINGS:
  material: GILDED_IRON
  material-type: SLIMEFUN
  repair-amount: 40

GILDED_IRON_BOOTS:
  material: GILDED_IRON
  material-type: SLIMEFUN
  repair-amount: 50

if the item is almost destroyed the slimy anvil work fine, but i think if the % go over 100 i get the error
this is the log  for the server
[latest.log](https://github.com/user-attachments/files/17194655/latest.log)

## Expected behavior (Required)

Repair up to 100% and dont wasted resources

## Server Log / Error Report

https://pastebin.com/BcqBt71a

## Environment (Required)

VERSION FOR SLIMFUN: Slimefun4-Dev1156
VERSION FOR SLIMYREPAIR: SlimyRepair - DEV 4 (git 790c4)
VERSION MC: 1.20.6
VERSION LAUNCHER: purpur-2233
VERSION JAVA : OpenJDK Runtime Environment Corretto-22.0.2.9.1 (build 22.0.2+9-FR)

![imagen](https://github.com/user-attachments/assets/6f0ae69b-e663-40f8-92e1-e062bcb32f18)
![imagen](https://github.com/user-attachments/assets/95a84c56-ab6e-4ba2-89f1-c1a0d485f447)
![imagen](https://github.com/user-attachments/assets/721e8a7b-7ff8-468f-9ab1-8295fd194af6)

**Comment by NCBPFluffyBear** [comment]
Hey there! Thanks for the report! Just fixed this issue, build is located here: https://blob.build/project/SlimyRepair
Please let me know if there are still issues, or close the issue if it has been fixed.

**Comment by goldenpunch101** [comment]
work perpect, tks for the fast fix
